---------------------------------------------------
# Estatística 2
---------------------------------------------------

In [70]:
#importando bibliotecas
import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy.stats import t
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import chi2_contingency
from statsmodels.formula.api import ols
from statsmodels.stats.multicomp import MultiComparison

---------------------------------------------------

## Teste T de Student 

 - É utilizado para ver se há dif entre duas amostras que possuem distrib. normal.
 - Variância Aproximada
 - Amostras independentes
---------------------------------------------------
 

In [50]:
# Média da hora paga por um profissional = 75 biros | amostra c/ 9 | desvpad 10

# ganhar menos de 80
x = t.cdf(1.5,8) 

#ganhar mais de 80
y = t.sf(1.5, 8)

#somatório de ambos os lados
z = x + y

print("ganhar menos de 80: ", x)
print("ganhar mais de 80: ", y)
print("Somatório: ", z)

ganhar menos de 80:  0.9139983540240443
ganhar mais de 80:  0.08600164597595565
Somatório:  0.9999999999999999


---------------------------------------------------
## Distribuição Binomial

- Um num fixo de experimentos
- 2 resultados apenas (sucesso ou fracaço | 0 ou 1)
- Mesma probabilidade em todos os eventos
- Experimentos independentes
---------------------------------------------------

In [51]:
# jogando 5x uma moeda
# cara 3x

# - N° x ocorreu evento | Testes | Probabilidades

prob = binom.pmf(3, 5, 0.5)

print("A probabilidade de dar 3x cara em 5 lances, é: ", prob)

A probabilidade de dar 3x cara em 5 lances, é:  0.31249999999999983


In [52]:
# Passar por 4 sinais de 4 tempos -> chance de pegar o sinal verde (0,1,2,3,4) 
# Sinal de 4 tempos: green yellow yellow red

nenhuma = binom.pmf(0, 4, 0.25)
uma = binom.pmf(1, 4, 0.25)
duas =binom.pmf(2, 4, 0.25)
tres = binom.pmf(3, 4, 0.25)
quatro = binom.pmf(4, 4, 0.25)

print("0: ", nenhuma)
print("1: ", uma)
print("2: ", duas)
print("3: ", tres)
print("4: ", quatro)

#somando
x = nenhuma+ uma+ duas+ tres + quatro

print("soma das chances: ", x )

0:  0.31640625
1:  0.4218750000000001
2:  0.21093750000000006
3:  0.046875000000000014
4:  0.00390625
soma das chances:  1.0000000000000002


In [53]:
# Sinais de dois tempos
binom.pmf (4, 4, 0.5)

0.0625

In [54]:
#prob acumulativa - Quando 
binom.cdf (4,4,0.25)

1.0

In [55]:
#concurso com 12 questões, a chance de acertar 7, 
#tendo cada questão 4 alternativas

# 7 eventos | 12 vezes | 0.25 de prob -> ocorrer 7 vezes um evento, 
# em 12 oportunidades com 25% de chance cada
binom.pmf(7,12,0.25)*100

1.1471271514892587

In [56]:
#acertar as 12
binom.pmf(12,12,0.25)

5.960464477539063e-08

---------------------------------------------------
## Distribuição Poisson

- Prob de eventos em um determinado tempo
- Os eventos a cada intervalo devem ser independentes
- Existem tabelas de probabilidade
---------------------------------------------------

 A média de acidentes por dia é 2

In [57]:
#chance de rolar 3:
a = poisson.pmf(3,2)

#chance de rolar menos de 3
b = poisson.cdf(3,2)

#rolar mais de 3
c =poisson.sf(3,2)

print("chance de rolar 3: ", a)
print("chance de rolar menos de 3: ", b)
print("chance de rolar mais de 3:: ", c)

chance de rolar 3:  0.18044704431548356
chance de rolar menos de 3:  0.857123460498547
chance de rolar mais de 3::  0.14287653950145296


In [58]:
#Rolar 3 ou menos: 
print("rolar 3 ou menos: ",a+c)

rolar 3 ou menos:  0.3233235838169365


In [59]:
poisson.cdf(3, 2) + poisson.sf(3, 2)

1.0

---------------------------------------------------
## Distribuição Poisson

- Saber se existe diferença significativa
- Ou se a diferença é fruto do acaso
---------------------------------------------------

In [64]:
#pessoas que leem novels - (1,1 lê | 1,2 não lê)

novel = np.array([[34, 12],[53,42]])
novel

array([[34, 12],
       [53, 42]])

In [68]:
# se o valor de p é maior que 0.05 não há diferença significativa
# Segundo valor é o pvalue
chi2_contingency(novel) # 0.05864926033220706, s/ dif sig

(3.575175241326703,
 0.05864926033220706,
 1,
 array([[28.38297872, 17.61702128],
        [58.61702128, 36.38297872]]))

In [69]:
novel2 = np.array([[100, 18],[500,200]])
chi2_contingency(novel2) #0.0035659852860587607, c/ dif sig

(8.492576124760276,
 0.0035659852860587607,
 1,
 array([[ 86.55256724,  31.44743276],
        [513.44743276, 186.55256724]]))